version: "3.8"

services:
  fastapi_jmx:
    image: jmeter-toolkit:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PIP_INDEX_URL: ${PIP_INDEX_URL:-https://pypi.tuna.tsinghua.edu.cn/simple}
    ports:
      - "18000:8000"
    volumes:
      - ./jmx_files:/app/jmx_files
      - ./jtl_files:/app/jtl_files
      - ./reports:/app/reports

